require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/FileName:
  Exclude:
    - lib/bp3-request_state.rb

Style/Documentation:
  Enabled: false
